// Simplified → Traditional Chinese conversion (replaces external OpenCC
// dependency).
//
// Pipeline (mirrors OpenCC s2t + TWVariants):
//   1. STPhrases: longest-match phrase substitution via daachorse AC
//   2. STCharacters: safe single-character HashMap fallback; ambiguous
//      one-to-many chars intentionally fall back to identity rather than
//      guessing a reading, so an uncovered 复 stays 复 instead of becoming
//      a plausible-looking but wrong 復
//   3. TWVariants: Taiwan-specific variant normalization
//
// Dictionary data is pre-generated by scripts/gen-s2t-tables.py into
// s2t_data.rs (static arrays). No runtime text parsing needed.

#[path = "s2t_data.rs"]
mod s2t_data;

use std::collections::HashMap;

use daachorse::{CharwiseDoubleArrayAhoCorasickBuilder, MatchKind as DaacMatchKind};

// Converter

/// Compiled SC→TC converter. Build once, reuse across calls.
pub struct S2TConverter {
    /// Phrase AC automaton (longest-match). Match value = index into
    /// `phrase_targets`.
    phrase_ac: daachorse::CharwiseDoubleArrayAhoCorasick<u32>,
    /// Target strings for phrase matches, parallel to AC pattern indices.
    /// Pre-normalized: TWVariants already applied at build time, so phrase
    /// outputs are in final TW form and need no further variant normalization.
    phrase_targets: Vec<String>,
    /// Single-character SC→TC map (fallback after phrase matching).
    char_map: HashMap<char, char>,
    /// TW variant normalization map (applied to char-level output only).
    tw_variant_map: HashMap<char, char>,
}

impl Default for S2TConverter {
    fn default() -> Self {
        Self::new()
    }
}

impl S2TConverter {
    /// Build the converter from pre-generated static tables.
    ///
    /// Panics if the daachorse AC build fails (should never happen with
    /// well-formed dictionary data).
    pub fn new() -> Self {
        // Build character maps from static arrays.
        let char_map: HashMap<char, char> = s2t_data::ST_CHARACTERS.iter().copied().collect();
        let tw_variant_map: HashMap<char, char> = s2t_data::TW_VARIANTS.iter().copied().collect();

        // Build phrase targets vec and AC patterns from static data. Pre-apply
        // TWVariants to phrase targets so they are in final TW form. This lets
        // us protect phrase output ranges from the TWVariants round without
        // losing variant normalization (it is baked in).
        let len = s2t_data::ST_PHRASES.len();
        let mut phrase_targets: Vec<String> = Vec::with_capacity(len);
        let mut patvals: Vec<(&str, u32)> = Vec::with_capacity(len);

        for (i, &(key, val)) in s2t_data::ST_PHRASES.iter().enumerate() {
            let normalized: String = val
                .chars()
                .map(|ch| *tw_variant_map.get(&ch).unwrap_or(&ch))
                .collect();
            phrase_targets.push(normalized);
            let idx = u32::try_from(i).expect("ST_PHRASES count exceeds u32");
            patvals.push((key, idx));
        }

        let phrase_ac = CharwiseDoubleArrayAhoCorasickBuilder::new()
            .match_kind(DaacMatchKind::LeftmostLongest)
            .build_with_values(patvals)
            .expect("s2t phrase AC build");

        Self {
            phrase_ac,
            phrase_targets,
            char_map,
            tw_variant_map,
        }
    }

    /// Convert Simplified Chinese text to Traditional Chinese (Taiwan variant).
    ///
    /// Protected-zone tracking: phrase substitutions produce pre-normalized
    /// output (TWVariants baked in at build time). Their byte ranges in the
    /// output buffer are recorded as protected zones. The TWVariants pass skips
    /// characters inside protected zones, preventing double-conversion while
    /// still normalizing character-level output.
    pub fn convert(&self, input: &str) -> String {
        // Pass 1+2 (interleaved): phrase AC matches + char-level fallback for
        // gaps.
        let mut out = String::with_capacity(input.len());

        // Protected zones: sorted, non-overlapping byte ranges of phrase
        // outputs.
        let mut protected: Vec<(usize, usize)> = Vec::new();
        let mut last_byte = 0;

        for mat in self.phrase_ac.leftmost_find_iter(input) {
            let start = mat.start();
            let end = mat.end();

            // Convert unmatched gap character-by-character.
            for ch in input[last_byte..start].chars() {
                out.push(self.convert_char(ch));
            }

            // Record protected zone and substitute phrase (already
            // pre-normalized).
            let zone_start = out.len();
            out.push_str(&self.phrase_targets[mat.value() as usize]);
            protected.push((zone_start, out.len()));

            last_byte = end;
        }

        // Convert remaining tail.
        for ch in input[last_byte..].chars() {
            out.push(self.convert_char(ch));
        }

        // Pass 3: TW variant normalization, skipping protected zones. Phrase
        // outputs are already in final form; only char-level output needs this.
        if self.tw_variant_map.is_empty() {
            return out;
        }
        let mut result = String::with_capacity(out.len());
        let mut byte_pos: usize = 0;
        let mut zone_idx: usize = 0;
        for ch in out.chars() {
            let ch_len = ch.len_utf8();
            // Advance past zones that end at or before this position.
            while zone_idx < protected.len() && protected[zone_idx].1 <= byte_pos {
                zone_idx += 1;
            }

            // After advancing, current zone (if any) has end > byte_pos, so we
            // only need to check whether we are past its start.
            let in_zone = zone_idx < protected.len() && byte_pos >= protected[zone_idx].0;
            if in_zone {
                result.push(ch);
            } else {
                result.push(*self.tw_variant_map.get(&ch).unwrap_or(&ch));
            }
            byte_pos += ch_len;
        }
        result
    }

    /// Convert a single character using STCharacters map.
    #[inline]
    fn convert_char(&self, ch: char) -> char {
        *self.char_map.get(&ch).unwrap_or(&ch)
    }

    /// Number of phrase patterns in the AC automaton.
    pub fn phrase_count(&self) -> usize {
        self.phrase_targets.len()
    }

    /// Number of character mappings.
    pub fn char_count(&self) -> usize {
        self.char_map.len()
    }

    /// Number of ambiguous character fallbacks intentionally left as identity.
    pub fn ambiguous_char_count(&self) -> usize {
        s2t_data::AMBIGUOUS_ST_CHARACTERS.len()
    }
}

#[cfg(test)]
#[path = "../../tests/unit/engine/s2t/tests.rs"]
mod tests;
