// Baseline mode for incremental adoption.
//
// Issue fingerprints: hash(rule_type + found text + file path).
// --update-baseline writes the baseline; --baseline reads and filters.

use std::collections::HashSet;
use std::path::Path;

use crate::rules::ruleset::Issue;

/// A baseline file is a JSON array of fingerprint strings.
#[derive(Debug, Default)]
pub struct Baseline {
    fingerprints: HashSet<String>,
}

impl Baseline {
    /// Load a baseline from a JSON file. Returns empty baseline if file
    /// does not exist.
    pub fn load(path: &Path) -> anyhow::Result<Self> {
        if !path.exists() {
            return Ok(Self::default());
        }
        let content = std::fs::read_to_string(path)?;
        let fps: Vec<String> = serde_json::from_str(&content)?;
        Ok(Self {
            fingerprints: fps.into_iter().collect(),
        })
    }

    /// Save baseline to a JSON file.
    ///
    /// Deliberately a plain write, not the tempfile-and-rename used by the
    /// cache and the stores. Rename swaps the directory entry, which changes
    /// four things a plain write gets right: it replaces a symlinked baseline
    /// instead of writing through it, it needs write permission on the
    /// directory rather than on the file, it silently overwrites a
    /// write-protected file instead of failing with EACCES, and it creates
    /// with the temp file's 0600 rather than honoring the umask. Atomicity
    /// buys little here because a torn baseline is regenerated by rerunning
    /// `--update-baseline`.
    pub fn save(&self, path: &Path) -> anyhow::Result<()> {
        let mut fps: Vec<&String> = self.fingerprints.iter().collect();
        fps.sort();
        let json = serde_json::to_string_pretty(&fps)?;
        std::fs::write(path, json)?;
        Ok(())
    }

    /// Check if an issue is in the baseline.
    pub fn contains(&self, file: &str, issue: &Issue) -> bool {
        let fp = fingerprint(file, issue);
        self.fingerprints.contains(&fp)
    }

    /// Add an issue fingerprint to the baseline.
    pub fn insert(&mut self, file: &str, issue: &Issue) {
        let fp = fingerprint(file, issue);
        self.fingerprints.insert(fp);
    }

    pub fn len(&self) -> usize {
        self.fingerprints.len()
    }

    pub fn is_empty(&self) -> bool {
        self.fingerprints.is_empty()
    }
}

/// Compute a stable fingerprint for an issue.
///
/// Hash of: rule_type + found text + file path.
/// This is intentionally position-independent so edits that shift line
/// numbers don't invalidate the baseline.
fn fingerprint(file: &str, issue: &Issue) -> String {
    let mut hasher = blake3::Hasher::new();
    let rule_str = serde_json::to_string(&issue.rule_type).unwrap_or_default();
    hasher.update(rule_str.as_bytes());
    hasher.update(b"|");
    hasher.update(issue.found.as_bytes());
    hasher.update(b"|");
    hasher.update(file.as_bytes());
    hasher.finalize().to_hex().to_string()
}

#[cfg(test)]
#[path = "../tests/unit/baseline/tests.rs"]
mod tests;
